name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn package 

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload JAR to GitHub Packages
        uses: actions/upload-artifact@v2
        with:
          name: spring-rest-hello-world.jar
          path: target/spring-rest-hello-world-1.0.jar
